// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.Warehouse.Persistence;

#nullable disable

namespace WaroTrans.Warehouse.Persistence.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20261007044512_AddWarehouseNavigationProperties")]
    partial class AddWarehouseNavigationProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("warehouse")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<short?>("CurrentLevelNo")
                        .HasColumnType("smallint")
                        .HasColumnName("current_level_no");

                    b.Property<Guid?>("CurrentStorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_storage_location_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierPackageBarcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supplier_package_barcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_containers");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("i_x_containers_barcode");

                    b.HasIndex("CurrentStorageLocationId")
                        .HasDatabaseName("i_x_containers_current_storage_location_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("i_x_containers_product_id");

                    b.ToTable("containers", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.InventoryStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContainerCount")
                        .HasColumnType("integer")
                        .HasColumnName("container_count");

                    b.Property<short>("LevelNo")
                        .HasColumnType("smallint")
                        .HasColumnName("level_no");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<Guid>("StorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("storage_location_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_inventory_stocks");

                    b.HasIndex("StorageLocationId")
                        .HasDatabaseName("i_x_inventory_stocks_storage_location_id");

                    b.HasIndex("ProductId", "StorageLocationId", "LevelNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_inventory_stocks_product_id_storage_location_id_level_no");

                    b.ToTable("inventory_stocks", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sku");

                    b.Property<string>("SupplierBarcode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supplier_barcode");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_products");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("i_x_products_sku");

                    b.HasIndex("SupplierBarcode")
                        .IsUnique()
                        .HasDatabaseName("i_x_products_supplier_barcode")
                        .HasFilter("supplier_barcode IS NOT NULL");

                    b.ToTable("products", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_product_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_product_categories_code");

                    b.ToTable("product_categories", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.StorageLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("p_k_storage_locations");

                    b.HasIndex("EndpointId")
                        .IsUnique()
                        .HasDatabaseName("i_x_storage_locations_endpoint_id");

                    b.ToTable("storage_locations", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.HasKey("Id")
                        .HasName("p_k_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_warehouses_code");

                    b.ToTable("warehouses", "warehouse");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.Container", b =>
                {
                    b.HasOne("WaroTrans.Warehouse.Entities.StorageLocation", "CurrentStorageLocation")
                        .WithMany()
                        .HasForeignKey("CurrentStorageLocationId")
                        .HasConstraintName("f_k_containers_storage_locations_current_storage_location_id");

                    b.HasOne("WaroTrans.Warehouse.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_containers_products_product_id");

                    b.Navigation("CurrentStorageLocation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WaroTrans.Warehouse.Entities.InventoryStock", b =>
                {
                    b.HasOne("WaroTrans.Warehouse.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_inventory_stocks_products_product_id");

                    b.HasOne("WaroTrans.Warehouse.Entities.StorageLocation", "StorageLocation")
                        .WithMany()
                        .HasForeignKey("StorageLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_inventory_stocks_storage_locations_storage_location_id");

                    b.Navigation("Product");

                    b.Navigation("StorageLocation");
                });
#pragma warning restore 612, 618
        }
    }
}
