// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.Transportation.Persistence;

#nullable disable

namespace WaroTrans.Transportation.Persistence.Migrations
{
    [DbContext(typeof(TransportationDbContext))]
    [Migration("20261003130937_AddTransportRequestDetail_DropTransportData")]
    partial class AddTransportRequestDetail_DropTransportData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("transportation")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.Transportation.Entities.TransportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_message");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<int>("PlanSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_schema_version");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<string>("RequestCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_code");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<string>("WorkflowInputs")
                        .HasColumnType("jsonb")
                        .HasColumnName("workflow_inputs");

                    b.HasKey("Id")
                        .HasName("p_k_transport_requests");

                    b.HasIndex("RequestCode")
                        .IsUnique()
                        .HasDatabaseName("i_x_transport_requests_request_code");

                    b.ToTable("transport_requests", "transportation");
                });

            modelBuilder.Entity("WaroTrans.Transportation.Entities.TransportRequestDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DestinationEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_endpoint_id");

                    b.Property<short>("DestinationLevelNo")
                        .HasColumnType("smallint")
                        .HasColumnName("destination_level_no");

                    b.Property<Guid?>("DestinationStorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_storage_location_id");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<Guid>("SourceEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_endpoint_id");

                    b.Property<short>("SourceLevelNo")
                        .HasColumnType("smallint")
                        .HasColumnName("source_level_no");

                    b.Property<Guid?>("SourceStorageLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_storage_location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_transport_request_details");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("i_x_transport_request_details_container_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_transport_request_details_status");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("i_x_transport_request_details_transport_request_id");

                    b.HasIndex("TransportRequestId", "ContainerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_transport_request_details_transport_request_id_container_id");

                    b.HasIndex("TransportRequestId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_transport_request_details_transport_request_id_sequence_no");

                    b.ToTable("transport_request_details", "transportation");
                });

            modelBuilder.Entity("WaroTrans.Transportation.Entities.TransportRequestDetail", b =>
                {
                    b.HasOne("WaroTrans.Transportation.Entities.TransportRequest", "TransportRequest")
                        .WithMany("Details")
                        .HasForeignKey("TransportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_transport_request_details_transport_requests_transport_requ~");

                    b.Navigation("TransportRequest");
                });

            modelBuilder.Entity("WaroTrans.Transportation.Entities.TransportRequest", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
