import { useState } from 'react'
import type { Account, AccountRole } from '@/shared/api/contracts'
import { Dialog } from '@/shared/ui/Dialog'
import { ACCOUNT_ROLES } from './constants'

interface AccountFormDialogProps {
  /** Account being edited; null creates a new one. */
  account: Account | null
  existingUsernames: string[]
  onClose: () => void
  onSave: (values: Pick<Account, 'username' | 'email' | 'fullName' | 'role'>) => void
}

export function AccountFormDialog({ account, existingUsernames, onClose, onSave }: AccountFormDialogProps) {
  const [username, setUsername] = useState(account?.username ?? '')
  const [email, setEmail] = useState(account?.email ?? '')
  const [fullName, setFullName] = useState(account?.fullName ?? '')
  const [role, setRole] = useState<AccountRole>(account?.role ?? 'STAFF')
  const [error, setError] = useState<string | null>(null)

  function submit() {
    const trimmed = username.trim()
    if (!trimmed || !email.trim() || !fullName.trim()) {
      setError('Username, email and full name are required.')
      return
    }
    if (account?.username !== trimmed && existingUsernames.includes(trimmed)) {
      setError('This username is already in use.')
      return
    }
    onSave({ username: trimmed, email: email.trim(), fullName: fullName.trim(), role })
  }

  return (
    <Dialog
      title={account ? 'Edit account' : 'Add account'}
      submitLabel={account ? 'Save changes' : 'Create account'}
      onClose={onClose}
      onSubmit={submit}
    >
      <label className="field">
        Username
        <input value={username} onChange={(event) => setUsername(event.target.value)} autoFocus />
      </label>
      <label className="field">
        Email
        <input type="email" value={email} onChange={(event) => setEmail(event.target.value)} />
      </label>
      <label className="field">
        Full name
        <input value={fullName} onChange={(event) => setFullName(event.target.value)} />
      </label>
      <label className="field">
        Role
        <select value={role} onChange={(event) => setRole(event.target.value as AccountRole)}>
          {ACCOUNT_ROLES.map((item) => (
            <option key={item} value={item}>
              {item}
            </option>
          ))}
        </select>
      </label>
      {!account ? <small className="field">A temporary password is generated by the server on creation.</small> : null}
      {error ? <small className="field" style={{ color: 'var(--red-ink)' }}>{error}</small> : null}
    </Dialog>
  )
}
