using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace WaroTrans.Navigation.Features.CreateEndpoint;

public static class CreateEndpointEndpoint
{
    public static void Map(IEndpointRouteBuilder endpoints)
    {
        endpoints.MapPost("/maps/{mapVersionId:guid}/endpoints", async (
            Guid mapVersionId,
            CreateEndpointRequest request,
            CreateEndpointHandler handler,
            CancellationToken cancellationToken) =>
        {
            var response = await handler.HandleAsync(mapVersionId, request, cancellationToken);
            return Results.Created($"/api/navigation/endpoints/{response.Id}", response);
        })
        .WithName("CreateEndpoint")
        .WithSummary("Create a navigation Endpoint on a draft map version")
        .WithDescription("Places a semantic robot destination (receiving, shelf access, outbound, parking, charging, maintenance, ...) on a DRAFT MapVersion. The business code EP-{NAME} is generated by the backend from Name.");
    }
}
