namespace WaroTrans.Navigation.Features.CreateEndpoint;

/// <summary>
/// Code is generated by IBusinessCodeGenerator from Name (EP-{NAME}) and is therefore not part of the request.
/// X/Y are map-frame coordinates in metres; Yaw is in radians.
/// </summary>
public sealed record CreateEndpointRequest(
    string Name,
    string EndpointType,
    double X,
    double Y,
    double Yaw,
    double PositionTolerance,
    double YawTolerance,
    bool? IsEnabled
);
