// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.Navigation.Persistence;

#nullable disable

namespace WaroTrans.Navigation.Persistence.Migrations
{
    [DbContext(typeof(NavigationDbContext))]
    [Migration("20260927043613_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("navigation")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.Navigation.Entities.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("direction");

                    b.Property<JsonDocument>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_version_id");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed");

                    b.HasKey("Id")
                        .HasName("p_k_edges");

                    b.HasIndex("Code")
                        .HasDatabaseName("i_x_edges_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_edges_is_active");

                    b.HasIndex("MapVersionId")
                        .HasDatabaseName("i_x_edges_map_version_id");

                    b.HasIndex("MapVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_edges_map_version_id_code");

                    b.ToTable("edges", "navigation");
                });

            modelBuilder.Entity("WaroTrans.Navigation.Entities.Endpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("endpoint_type");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_version_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<double>("PositionTolerance")
                        .HasColumnType("double precision")
                        .HasColumnName("position_tolerance");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.Property<double>("Yaw")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw");

                    b.Property<double>("YawTolerance")
                        .HasColumnType("double precision")
                        .HasColumnName("yaw_tolerance");

                    b.HasKey("Id")
                        .HasName("p_k_endpoints");

                    b.HasIndex("Code")
                        .HasDatabaseName("i_x_endpoints_code");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("i_x_endpoints_is_enabled");

                    b.HasIndex("MapVersionId")
                        .HasDatabaseName("i_x_endpoints_map_version_id");

                    b.HasIndex("MapVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_endpoints_map_version_id_code");

                    b.ToTable("endpoints", "navigation");
                });

            modelBuilder.Entity("WaroTrans.Navigation.Entities.EndpointGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_version_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SelectionPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("selection_policy");

                    b.HasKey("Id")
                        .HasName("p_k_endpoint_groups");

                    b.HasIndex("Code")
                        .HasDatabaseName("i_x_endpoint_groups_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_endpoint_groups_is_active");

                    b.HasIndex("MapVersionId")
                        .HasDatabaseName("i_x_endpoint_groups_map_version_id");

                    b.HasIndex("MapVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_endpoint_groups_map_version_id_code");

                    b.ToTable("endpoint_groups", "navigation");
                });

            modelBuilder.Entity("WaroTrans.Navigation.Entities.EndpointGroupMember", b =>
                {
                    b.Property<Guid>("EndpointGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_group_id");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("endpoint_id");

                    b.HasKey("EndpointGroupId", "EndpointId")
                        .HasName("p_k_endpoint_group_members");

                    b.HasIndex("EndpointId")
                        .HasDatabaseName("i_x_endpoint_group_members_endpoint_id");

                    b.ToTable("endpoint_group_members", "navigation");
                });

            modelBuilder.Entity("WaroTrans.Navigation.Entities.MapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MapUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("map_uri");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<double>("OriginX")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_x");

                    b.Property<double>("OriginY")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_y");

                    b.Property<double>("OriginYaw")
                        .HasColumnType("double precision")
                        .HasColumnName("origin_yaw");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<double>("Resolution")
                        .HasColumnType("double precision")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("p_k_map_versions");

                    b.HasIndex("WarehouseId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_map_versions_warehouse_id_version_no");

                    b.ToTable("map_versions", "navigation");
                });

            modelBuilder.Entity("WaroTrans.Navigation.Entities.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<JsonDocument>("Geometry")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("geometry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_version_id");

                    b.Property<double?>("MaxSpeed")
                        .HasColumnType("double precision")
                        .HasColumnName("max_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id")
                        .HasName("p_k_zones");

                    b.HasIndex("Code")
                        .HasDatabaseName("i_x_zones_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("i_x_zones_is_active");

                    b.HasIndex("MapVersionId")
                        .HasDatabaseName("i_x_zones_map_version_id");

                    b.HasIndex("MapVersionId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_zones_map_version_id_code");

                    b.ToTable("zones", "navigation");
                });
#pragma warning restore 612, 618
        }
    }
}
