// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.WorkflowExecution.Persistence;

#nullable disable

namespace WaroTrans.WorkflowExecution.Persistence.Migrations
{
    [DbContext(typeof(WorkflowExecutionDbContext))]
    [Migration("20261008023819_AddWorkflowStepConfig")]
    partial class AddWorkflowStepConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("execution")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.HandoverConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<string>("Evidence")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("HandoverType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("handover_type");

                    b.Property<Guid>("JobStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_step_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.HasKey("Id")
                        .HasName("p_k_handover_confirmations");

                    b.HasIndex("JobStepId")
                        .IsUnique()
                        .HasDatabaseName("i_x_handover_confirmations_job_step_id");

                    b.ToTable("handover_confirmations", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_values");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_code");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_message");

                    b.Property<string>("JobNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_no");

                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("map_version_id");

                    b.Property<DateTimeOffset?>("QueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("p_k_jobs");

                    b.HasIndex("JobNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_jobs_job_no");

                    b.ToTable("jobs", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContainerId")
                        .HasColumnType("uuid")
                        .HasColumnName("container_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset?>("LoadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaded_at");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TransportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("transport_request_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_job_containers");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("i_x_job_containers_container_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_job_containers_status");

                    b.HasIndex("TransportRequestId")
                        .HasDatabaseName("i_x_job_containers_transport_request_id");

                    b.HasIndex("JobId", "ContainerId")
                        .IsUnique()
                        .HasDatabaseName("i_x_job_containers_job_id_container_id");

                    b.HasIndex("JobId", "SequenceNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_job_containers_job_id_sequence_no");

                    b.ToTable("job_containers", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("JobTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_task_id");

                    b.Property<string>("OutputValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("output_values");

                    b.Property<string>("ResolvedInputs")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("resolved_inputs");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_type");

                    b.Property<Guid?>("TargetEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_endpoint_id");

                    b.Property<Guid>("WorkflowStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_step_id");

                    b.HasKey("Id")
                        .HasName("p_k_job_steps");

                    b.HasIndex("JobTaskId")
                        .HasDatabaseName("i_x_job_steps_job_task_id");

                    b.ToTable("job_steps", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContextValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("context_values");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("failure_code");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_task_id");

                    b.HasKey("Id")
                        .HasName("p_k_job_tasks");

                    b.HasIndex("JobId")
                        .HasDatabaseName("i_x_job_tasks_job_id");

                    b.ToTable("job_tasks", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("VariablesSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("variables_schema");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id")
                        .HasName("p_k_workflows");

                    b.HasIndex("Code", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("i_x_workflows_code_version_no");

                    b.ToTable("workflows", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<string>("InputBindings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_bindings");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("OnFailure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("on_failure");

                    b.Property<int>("RetryBackoffSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("retry_backoff_seconds");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("step_key");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("step_type");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_task_id");

                    b.HasKey("Id")
                        .HasName("p_k_workflow_steps");

                    b.HasIndex("WorkflowTaskId")
                        .HasDatabaseName("i_x_workflow_steps_workflow_task_id");

                    b.ToTable("workflow_steps", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<string>("TaskKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("task_key");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id")
                        .HasName("p_k_workflow_tasks");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("i_x_workflow_tasks_workflow_id");

                    b.ToTable("workflow_tasks", "execution");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.HandoverConfirmation", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.JobStep", "JobStep")
                        .WithOne("HandoverConfirmation")
                        .HasForeignKey("WaroTrans.WorkflowExecution.Entities.HandoverConfirmation", "JobStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_handover_confirmations_job_steps_job_step_id");

                    b.Navigation("JobStep");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobContainer", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.Job", "Job")
                        .WithMany("JobContainers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_job_containers_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobStep", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.JobTask", "JobTask")
                        .WithMany("JobSteps")
                        .HasForeignKey("JobTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_job_steps_job_tasks_job_task_id");

                    b.Navigation("JobTask");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobTask", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.Job", "Job")
                        .WithMany("JobTasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_job_tasks_jobs_job_id");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.WorkflowStep", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.WorkflowTask", "WorkflowTask")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_workflow_steps_workflow_tasks_workflow_task_id");

                    b.Navigation("WorkflowTask");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.WorkflowTask", b =>
                {
                    b.HasOne("WaroTrans.WorkflowExecution.Entities.Workflow", "Workflow")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_workflow_tasks_workflows_workflow_id");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.Job", b =>
                {
                    b.Navigation("JobContainers");

                    b.Navigation("JobTasks");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobStep", b =>
                {
                    b.Navigation("HandoverConfirmation");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.JobTask", b =>
                {
                    b.Navigation("JobSteps");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.Workflow", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("WaroTrans.WorkflowExecution.Entities.WorkflowTask", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
