import { JobSummary } from '../../shared/types/contracts';

export interface AppJobItem extends JobSummary {
  isMine: boolean;
  routeText: string;
  payloadSummary: string;
}

export const MOCK_JOBS: AppJobItem[] = [
  {
    id: 'JOB-2026-0881',
    jobNo: 'JOB-2026-0881',
    workflowCode: 'INBOUND_PUTAWAY',
    workflowName: 'Inbound Putaway',
    status: 'RUNNING',
    assignedRobotCode: 'AMR-01',
    etaSeconds: 45,
    sourceEndpointCode: 'DOCK-01',
    destinationEndpointCode: 'RACK-A02',
    activeStepTitle: 'AMR moving to Rack A-02 for operator unload',
    containerCount: 1,
    isMine: true,
    routeText: 'DOCK-01 (Receiving) ➔ RACK-A02 (Storage Zone A)',
    payloadSummary: 'Slot 1: BOX-101 (45 pcs - Industrial Sensor)',
    createdAtUtc: new Date(Date.now() - 5 * 60000).toISOString(),
    slots: [
      {
        slotNo: 1,
        slotLabel: 'Slot 1 (Front)',
        containerBarcode: 'BOX-101',
        productName: 'Optical Proximity Sensor X4',
        quantity: 45,
        action: 'UNLOAD',
      },
      {
        slotNo: 2,
        slotLabel: 'Slot 2 (Mid)',
        action: 'EMPTY',
      },
      {
        slotNo: 3,
        slotLabel: 'Slot 3 (Rear)',
        action: 'EMPTY',
      },
    ],
    steps: [
      {
        sequenceNo: 1,
        type: 'CHECK',
        title: 'Payload Pre-Check',
        description: 'Verify container latch & weight limit at Dock 01',
        status: 'COMPLETED',
        targetEndpointCode: 'DOCK-01',
      },
      {
        sequenceNo: 2,
        type: 'MOVE',
        title: 'Transit to Zone A',
        description: 'Autonomous navigation along Main Transit Corridor',
        status: 'EXECUTING',
        targetEndpointCode: 'RACK-A02',
        timeRemainingSeconds: 45,
      },
      {
        sequenceNo: 3,
        type: 'HUMAN_INTERACTION',
        title: 'Operator Unload & Barcode Scan',
        description: 'Confirm physical placement of BOX-101 into Rack A-02 Bin 03',
        status: 'PENDING',
        targetEndpointCode: 'RACK-A02',
      },
    ],
  },
  {
    id: 'JOB-2026-0882',
    jobNo: 'JOB-2026-0882',
    workflowCode: 'OUTBOUND_RETRIEVAL',
    workflowName: 'Outbound Retrieval',
    status: 'QUEUED',
    assignedRobotCode: 'AMR-02',
    etaSeconds: 210,
    sourceEndpointCode: 'RACK-B04',
    destinationEndpointCode: 'DOCK-04',
    activeStepTitle: 'Awaiting AMR assignment confirmation',
    containerCount: 2,
    isMine: false,
    routeText: 'RACK-B04 (Zone B Bulk) ➔ DOCK-04 (Shipping Bay)',
    payloadSummary: 'Slot 1 & 2: BOX-204, BOX-205 (90 pcs)',
    createdAtUtc: new Date(Date.now() - 15 * 60000).toISOString(),
    slots: [
      {
        slotNo: 1,
        slotLabel: 'Slot 1 (Front)',
        containerBarcode: 'BOX-204',
        productName: 'Pneumatic Actuator Valve',
        quantity: 50,
        action: 'PICKUP',
      },
      {
        slotNo: 2,
        slotLabel: 'Slot 2 (Mid)',
        containerBarcode: 'BOX-205',
        productName: 'Heavy Duty Coupler 20mm',
        quantity: 40,
        action: 'PICKUP',
      },
      {
        slotNo: 3,
        slotLabel: 'Slot 3 (Rear)',
        action: 'EMPTY',
      },
    ],
    steps: [
      {
        sequenceNo: 1,
        type: 'MOVE',
        title: 'Navigate to Rack B04',
        description: 'AMR moving from Depot to Bulk Racks',
        status: 'READY',
        targetEndpointCode: 'RACK-B04',
      },
      {
        sequenceNo: 2,
        type: 'HUMAN_INTERACTION',
        title: 'Load Outbound Containers',
        description: 'Place BOX-204 and BOX-205 onto trays 1 & 2',
        status: 'PENDING',
        targetEndpointCode: 'RACK-B04',
      },
      {
        sequenceNo: 3,
        type: 'MOVE',
        title: 'Transport to Dock 04',
        description: 'AMR transit to Outbound Staging',
        status: 'PENDING',
        targetEndpointCode: 'DOCK-04',
      },
    ],
  },
  {
    id: 'JOB-2026-0879',
    jobNo: 'JOB-2026-0879',
    workflowCode: 'INTERNAL_RELOCATION',
    workflowName: 'Internal Relocation',
    status: 'COMPLETED',
    assignedRobotCode: 'AMR-01',
    sourceEndpointCode: 'RACK-A01',
    destinationEndpointCode: 'RACK-A09',
    activeStepTitle: 'Workflow completed successfully',
    containerCount: 1,
    isMine: true,
    routeText: 'RACK-A01 ➔ RACK-A09 (Zone A Inner)',
    payloadSummary: 'Slot 2: TOTE-088 (20 pcs - Relay Modules)',
    createdAtUtc: new Date(Date.now() - 45 * 60000).toISOString(),
    slots: [
      {
        slotNo: 1,
        slotLabel: 'Slot 1 (Front)',
        action: 'EMPTY',
      },
      {
        slotNo: 2,
        slotLabel: 'Slot 2 (Mid)',
        containerBarcode: 'TOTE-088',
        productName: 'Relay Modules 24V',
        quantity: 20,
        action: 'UNLOAD',
      },
      {
        slotNo: 3,
        slotLabel: 'Slot 3 (Rear)',
        action: 'EMPTY',
      },
    ],
    steps: [
      {
        sequenceNo: 1,
        type: 'MOVE',
        title: 'Pickup Transit',
        description: 'Moved to Rack A01',
        status: 'COMPLETED',
      },
      {
        sequenceNo: 2,
        type: 'HUMAN_INTERACTION',
        title: 'Relocate Tote',
        description: 'Loaded TOTE-088 onto slot 2',
        status: 'COMPLETED',
      },
      {
        sequenceNo: 3,
        type: 'MOVE',
        title: 'Deliver to Rack A09',
        description: 'Transit and drop-off verified',
        status: 'COMPLETED',
      },
    ],
  },
  {
    id: 'JOB-2026-0878',
    jobNo: 'JOB-2026-0878',
    workflowCode: 'PAYLOAD_RECOVERY',
    workflowName: 'Payload Recovery',
    status: 'COMPLETED',
    assignedRobotCode: 'AMR-02',
    sourceEndpointCode: 'AISLE-02',
    destinationEndpointCode: 'DEPOT-01',
    activeStepTitle: 'Fault cleared & payload safely returned to Depot',
    containerCount: 1,
    isMine: false,
    routeText: 'AISLE-02 (Corridor) ➔ DEPOT-01 (Maintenance Bay)',
    payloadSummary: 'Slot 1: TOTE-012 (Secured)',
    createdAtUtc: new Date(Date.now() - 120 * 60000).toISOString(),
    slots: [
      {
        slotNo: 1,
        slotLabel: 'Slot 1 (Front)',
        containerBarcode: 'TOTE-012',
        productName: 'Recovered Payload Box',
        quantity: 1,
        action: 'UNLOAD',
      },
      {
        slotNo: 2,
        slotLabel: 'Slot 2 (Mid)',
        action: 'EMPTY',
      },
      {
        slotNo: 3,
        slotLabel: 'Slot 3 (Rear)',
        action: 'EMPTY',
      },
    ],
    steps: [],
  },
];
