// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.BuildingBlocks.Persistence.CodeSequences;

#nullable disable

namespace WaroTrans.BuildingBlocks.Persistence.CodeSequences.Migrations
{
    [DbContext(typeof(CodeSequenceDbContext))]
    partial class CodeSequenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.BuildingBlocks.Persistence.CodeSequences.CodeSequence", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset?>("DayBucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("day_bucket");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.HasKey("Key");

                    b.ToTable("code_sequences", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
