// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WaroTrans.Fleet.Persistence;

#nullable disable

namespace WaroTrans.Fleet.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    partial class FleetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WaroTrans.Fleet.Entities.DispatchDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("CandidateEvaluations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("candidate_evaluations");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("RobotId")
                        .HasColumnType("uuid")
                        .HasColumnName("robot_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_dispatch_decisions");

                    b.HasIndex("JobId")
                        .HasDatabaseName("i_x_dispatch_decisions_job_id");

                    b.ToTable("dispatch_decisions", "fleet");
                });

            modelBuilder.Entity("WaroTrans.Fleet.Entities.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("EndReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("end_reason");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid")
                        .HasColumnName("robot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_job_assignments");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("i_x_job_assignments_job_id")
                        .HasFilter("status IN ('PENDING_ACK', 'ACKNOWLEDGED', 'ACTIVE')");

                    b.HasIndex("RobotId")
                        .IsUnique()
                        .HasDatabaseName("i_x_job_assignments_robot_id")
                        .HasFilter("status IN ('PENDING_ACK', 'ACKNOWLEDGED', 'ACTIVE')");

                    b.ToTable("job_assignments", "fleet");
                });

            modelBuilder.Entity("WaroTrans.Fleet.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AngularVelocity")
                        .HasColumnType("double precision")
                        .HasColumnName("angular_velocity");

                    b.Property<decimal>("BatteryPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("battery_percent");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentCommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_command_id");

                    b.Property<Guid>("CurrentMapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_map_version_id");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<Guid?>("LastHeartbeatBootId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_heartbeat_boot_id");

                    b.Property<long?>("LastHeartbeatSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_heartbeat_sequence");

                    b.Property<DateTimeOffset?>("LastTelemetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_telemetry_at");

                    b.Property<Guid?>("LastTelemetryBootId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_telemetry_boot_id");

                    b.Property<long?>("LastTelemetrySequence")
                        .HasColumnType("bigint")
                        .HasColumnName("last_telemetry_sequence");

                    b.Property<double?>("LinearVelocity")
                        .HasColumnType("double precision")
                        .HasColumnName("linear_velocity");

                    b.Property<string>("LocalizationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localization_status");

                    b.Property<string>("MapVersionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("map_version_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("NavigationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("navigation_status");

                    b.Property<double>("PoseX")
                        .HasColumnType("double precision")
                        .HasColumnName("pose_x");

                    b.Property<double>("PoseY")
                        .HasColumnType("double precision")
                        .HasColumnName("pose_y");

                    b.Property<double>("PoseYaw")
                        .HasColumnType("double precision")
                        .HasColumnName("pose_yaw");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("p_k_robots");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_robots_code");

                    b.HasIndex("IsOnline")
                        .HasDatabaseName("i_x_robots_is_online");

                    b.HasIndex("LastHeartbeatAt")
                        .HasDatabaseName("i_x_robots_last_heartbeat_at");

                    b.ToTable("robots", "fleet");
                });

            modelBuilder.Entity("WaroTrans.Fleet.Entities.RobotCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acked_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<Guid?>("JobAssignmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_assignment_id");

                    b.Property<Guid?>("JobStepId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_step_id");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<string>("RejectReasonCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reject_reason_code");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid")
                        .HasColumnName("robot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetCommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_command_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("p_k_robot_commands");

                    b.HasIndex("JobAssignmentId")
                        .HasDatabaseName("i_x_robot_commands_job_assignment_id");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("i_x_robot_commands_robot_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_robot_commands_status");

                    b.HasIndex("RobotId", "Status")
                        .HasDatabaseName("i_x_robot_commands_robot_id_status");

                    b.ToTable("robot_commands", "fleet");
                });

            modelBuilder.Entity("WaroTrans.Fleet.Entities.RobotStateEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("from_status");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid")
                        .HasColumnName("robot_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("p_k_robot_state_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("i_x_robot_state_events_occurred_at");

                    b.HasIndex("RobotId")
                        .HasDatabaseName("i_x_robot_state_events_robot_id");

                    b.ToTable("robot_state_events", "fleet");
                });
#pragma warning restore 612, 618
        }
    }
}
